import { CaseStudyItem } from './types';

export const caseStudies: CaseStudyItem[] = [
  {
    id: 'case-autonomous-claims-orchestration',
    slug: 'autonomous-claims-orchestration',
    title: 'Autonomous Claims Adjudication & Clinical Record Extraction',
    clientDescriptor: 'Major Regional Healthcare Network (Confidential Enterprise)',
    industry: 'Healthcare & Health Insurance',
    challenge: 'The healthcare provider experienced heavy clinical documentation backlog and 14-day turnaround delays in prior authorization adjudication. Medical records were trapped in unstructured PDF physician notes, leading to repeated claim re-submissions and clinician administrative fatigue.',
    system: 'NexAgent deployed a private, sovereign on-premise Model-010 inference cluster connected directly to the hospital’s FHIR-compliant Epic electronic health record system. The system uses specialized SNOMED-CT and ICD-10-CM clinical parsers operating behind local hospital firewalls.',
    automation: 'Upon physician treatment ordering, the system autonomously extracts the relevant patient chart history, formats an adjudication packet against insurer clinical policy guidelines, checks for missing clinical justifications, and submits the dossier electronically without manual clinical intervention.',
    outcome: 'Eliminated manual chart extraction backlogs, reduced prior authorization turnarounds from 14 days to same-day determinations, and cut documentation rework across attending clinical staff without exposing patient health records to public cloud endpoints.',
    verifiedArchitecture: {
      latency: 'Sub-350ms entity extraction per clinical page',
      throughput: '12,000+ daily patient records processed',
      deploymentEnclave: 'On-premise Bare-Metal Sovereign GPU Enclave',
      compliance: 'HIPAA, HITECH, SOC 2 Type II Certified',
    },
    keyLessons: [
      'Clinical ontology enforcement must happen at the model level rather than via regex post-processing.',
      'Clinicians embrace autonomous systems when presented with explicit citations linking back to original clinical chart entries.',
      'Sovereign on-premise inference is an absolute prerequisite for healthcare institutional buy-in.',
    ],
    relatedSolutions: ['documentation-automation', 'business-automation'],
    relatedTechnology: ['ai-agents', 'cloud-infrastructure'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Build a Similar Healthcare Architecture',
    seo: {
      title: 'Case Study: Autonomous Claims Adjudication & Clinical Extraction | NexAgent',
      description: 'How a major healthcare network implemented sovereign Model-010 inference to automate clinical prior authorizations and EHR record reconciliation.',
      canonicalUrl: 'https://nexagent.group/case-studies/autonomous-claims-orchestration',
    },
  },
  {
    id: 'case-global-treasury-reconciliation',
    slug: 'global-treasury-reconciliation',
    title: 'Sub-Second Multi-Custodian Treasury & Ledger Settlement',
    clientDescriptor: 'Institutional Asset Custodian & Clearing House (Confidential)',
    industry: 'Financial Services & Capital Markets',
    challenge: 'Reconciling daily multi-currency cross-border trade settlements across 18 international clearing banks required a 40-person operational accounting team. Mismatches due to timestamp skews and rounding differences routinely delayed overnight cash settlement.',
    system: 'NexAgent implemented the NexEvent gRPC event mesh paired with a deterministic multi-agent reconciliation arbiter. The system ingests ISO 20022 and SWIFT MT settlement feeds in real time, matching ledger entries into an in-memory two-phase commit state machine.',
    automation: 'Autonomous reconciliation agents continuously identify rounding variances, match corresponding counterparty entries across disparate ledger formats, and automatically book adjustment entries within strict pre-authorized variance thresholds.',
    outcome: 'Achieved automated straight-through processing for 99.4% of daily multi-currency settlement volumes, eliminating overnight accounting delays and reducing settlement risk exposure.',
    verifiedArchitecture: {
      latency: 'Sub-15ms reconciliation time per batch',
      throughput: 'Up to 80,000 transactions per second burst capacity',
      deploymentEnclave: 'Private Cloud Dedicated Interconnect (London & Frankfurt)',
      compliance: 'ISO 27001, SOC 2, PCI-DSS Level 1',
    },
    keyLessons: [
      'Financial ledgers require deterministic two-phase commit safeguards before any automated balancing entry is committed.',
      'High-throughput event streaming eliminates the need for batch end-of-day synchronization.',
      'Granular audit trails detailing every matching parameter are vital for regulatory compliance examinations.',
    ],
    relatedSolutions: ['business-automation', 'crm-systems'],
    relatedTechnology: ['automation', 'software'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Build a Similar Financial System',
    seo: {
      title: 'Case Study: Sub-Second Multi-Custodian Treasury Reconciliation | NexAgent',
      description: 'How an institutional asset custodian deployed the NexEvent real-time mesh to automate multi-currency ledger reconciliation and settlement straight-through processing.',
      canonicalUrl: 'https://nexagent.group/case-studies/global-treasury-reconciliation',
    },
  },
  {
    id: 'case-distributed-guest-voice-mesh',
    slug: 'distributed-guest-voice-mesh',
    title: 'Sub-180ms Conversational Voice Reservation Mesh',
    clientDescriptor: 'Luxury Hospitality Group (Confidential Portfolio)',
    industry: 'Hospitality & Luxury Travel',
    challenge: 'A luxury hospitality group with 24 international properties experienced severe call abandonment rates during peak seasonal booking windows. Legacy IVR telephone systems frustrated high-net-worth guests who demanded immediate, natural concierge assistance.',
    system: 'NexAgent deployed a distributed WebRTC voice mesh connected directly to the group’s central Oracle Opera Property Management System. Voice agents operate with streaming neural acoustic separation, natural turn-taking, and instant interruption detection.',
    automation: 'The conversational voice system handles end-to-end telephone room reservations, confirms real-time suite availability, processes PCI-compliant tokenized payment authorizations, and dispatches tailored reservation confirmations instantly.',
    outcome: 'Zero wait times during peak seasonal surge windows, capturing all incoming direct booking revenue without expanding seasonal call-center headcount.',
    verifiedArchitecture: {
      latency: '168ms median roundtrip voice audio latency',
      throughput: 'Concurrent multi-property voice streams across 14 global POPs',
      deploymentEnclave: 'Edge WebRTC Media Mesh',
      compliance: 'PCI-DSS Tokenized Payment Enclave, GDPR',
    },
    keyLessons: [
      'Sub-200ms latency is mandatory for telephone voice adoption; higher latencies cause conversation collisions.',
      'Voice agents must handle interruptions instantaneously within 50ms to feel natural to discerning callers.',
      'Deep real-time PMS inventory integration is required to prevent accidental overbooking.',
    ],
    relatedSolutions: ['sales-automation', 'business-automation'],
    relatedTechnology: ['voice-ai', 'ai-agents'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Deploy Voice AI Architecture',
    seo: {
      title: 'Case Study: Sub-180ms Conversational Voice Reservation Mesh | NexAgent',
      description: 'How a luxury hotel group deployed NexAgent WebRTC voice runtimes to eliminate booking wait times and automate room reservations.',
      canonicalUrl: 'https://nexagent.group/case-studies/distributed-guest-voice-mesh',
    },
  },
];
