import { ProductItem } from './types';

export const products: ProductItem[] = [
  {
    id: 'prod-model-010',
    slug: 'model-010',
    name: 'Model-010: Autonomous Neural Runtime Engine',
    category: 'Neural Runtime',
    isCustomSystem: false,
    summary: 'Proprietary enterprise neural runtime engineered for deterministic workflow execution, 16-head sparse MoE routing, and sub-100ms inference.',
    description: 'Model-010 is NexAgent’s flagship neural engine, specifically optimized for high-concurrency enterprise automation tasks rather than generic conversational chatbots. Featuring specialized weights for schema extraction, tool execution, and deterministic consensus, Model-010 operates within sovereign enterprise enclaves with zero external cloud dependencies.',
    capabilities: [
      '16-Head Sparse Mixture-of-Experts (MoE) Routing',
      'Sub-100ms Time-to-First-Token Inference Benchmark',
      'Deterministic JSON Schema & Action Constraint Validation',
      'Cryptographic State Rollback & Rollforward Protocol',
      'Native Bare-Metal Deployment on NVIDIA H100 / B200 Systems',
    ],
    useCases: [
      'Mission-critical enterprise workflow automation where hallucinations cannot be tolerated',
      'High-throughput real-time voice and conversational audio feature processing',
      'Sovereign on-premise document adjudication in defense, healthcare, and finance',
      'Autonomous multi-agent task execution and state machine orchestration',
    ],
    targetOrganizations: [
      'Fortune 500 enterprise engineering and digital transformation divisions',
      'Regulated financial institutions requiring on-premise neural compute',
      'Healthcare and biomedical groups subject to strict data sovereignty mandates',
    ],
    relatedTechnology: ['ai-agents', 'cloud-infrastructure', 'voice-ai'],
    relatedSolutions: ['business-automation', 'documentation-automation'],
    documentationUrl: '/technology',
    demoUrl: '/core',
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Request Model-010 Evaluation',
    seo: {
      title: 'Model-010 | Autonomous Neural Runtime Engine | NexAgent Products',
      description: 'Model-010 is NexAgent’s proprietary enterprise neural runtime engineered for deterministic workflow execution, 16-head sparse MoE routing, and sub-100ms inference.',
      canonicalUrl: 'https://nexagent.group/products/model-010',
    },
  },
  {
    id: 'prod-event-mesh-runtime',
    slug: 'event-mesh-runtime',
    name: 'NexEvent: Enterprise gRPC & State Synchronization Fabric',
    category: 'Event Fabric',
    isCustomSystem: false,
    summary: 'High-throughput, zero-loss distributed event mesh connecting autonomous agent runtimes with legacy enterprise core systems at microsecond latencies.',
    description: 'NexEvent is the connective nervous system of the NexAgent operating platform. Built in Go and Rust with strict Protobuf v3 schemas, it routes state transitions between autonomous agent clusters, enterprise ERPs, and legacy mainframes with two-phase commit transaction guarantees.',
    capabilities: [
      'Sub-500 Microsecond Message Transit Latency',
      'Strict Protocol Buffers (Protobuf v3) Schema Enforcement',
      'Distributed Two-Phase Commit Transaction Coordination',
      'Hardware-Encrypted Zero-Trust mTLS Data In-Transit',
      'Horizontal Auto-Scaling up to 100,000 Events/Sec per Node',
    ],
    useCases: [
      'Real-time bi-directional synchronization between CRMs, ERPs, and AI agents',
      'High-frequency ledger updates across distributed multi-region enterprise data stores',
      'Asynchronous webhook ingestion and replay buffering during backend maintenance windows',
    ],
    targetOrganizations: [
      'Enterprises with distributed legacy ERP and CRM ecosystems seeking real-time unification',
      'Fintech and clearing organizations requiring zero-loss message processing',
      'Supply chain operators coordinating high-volume IoT and logistics feeds',
    ],
    relatedTechnology: ['automation', 'software', 'cloud-infrastructure'],
    relatedSolutions: ['crm-systems', 'business-automation'],
    documentationUrl: '/technology',
    status: 'PUBLISHED',
    readiness: 'IN_DEVELOPMENT',
    ctaText: 'Discuss Event Mesh Integration',
    seo: {
      title: 'NexEvent | High-Throughput Enterprise Event Mesh | NexAgent Products',
      description: 'Enterprise gRPC event mesh and real-time state synchronization fabric connecting AI agent runtimes with legacy ERP and database infrastructure.',
      canonicalUrl: 'https://nexagent.group/products/event-mesh-runtime',
    },
  },
];
