import { SolutionItem } from './types';

export const solutions: SolutionItem[] = [
  {
    id: 'sol-business-automation',
    slug: 'business-automation',
    name: 'Autonomous Business Operations & Workflow Automation',
    category: 'Automation',
    summary: 'End-to-end enterprise workflow automation replacing manual data re-entry, invoice reconciliation, and cross-department routing with autonomous agent coordination.',
    problem: 'Enterprise departments waste thousands of skilled labor hours copying data across disparate ERPs, CRMs, spreadsheets, and ticketing portals. Human routing introduces delays, transcription errors, and operational bottlenecks.',
    traditionalBreakdown: [
      'Fragile point-to-point Zapier/Make automations break whenever an API schema changes.',
      'RPA screen-scraping bots fail when UI layouts shift by a single pixel.',
      'Manual verification creates 48–72 hour delays in transaction settlement and approvals.',
      'Zero auditable context remains when automated scripts produce incorrect downstream records.',
    ],
    approach: 'NexAgent replaces brittle script-based automation with cognitive multi-agent workflows. Our systems understand semantic document structure, validate business rules using Model-010 reasoning, and execute two-phase commit transactions into backend enterprise databases with immutable audit logs.',
    systemComponents: [
      {
        name: 'Autonomous Perception Layer',
        description: 'Multi-modal document and event parsers converting PDFs, emails, invoices, and EDI feeds into structured JSON schemas.',
        badge: 'Ingress',
      },
      {
        name: 'Model-010 Consensus Engine',
        description: 'Multi-agent arbitration checking contract clauses, pricing tiers, and regulatory bounds before approving actions.',
        badge: 'Intelligence',
      },
      {
        name: 'Two-Phase Commit Dispatcher',
        description: 'Idempotent transactional gateway committing records simultaneously across SAP, Oracle, and Salesforce with instant rollback.',
        badge: 'Automation',
      },
      {
        name: 'Immutable Audit Ledger',
        description: 'Cryptographic time-stamped record of all prompts, reasoning steps, tool executions, and database responses.',
        badge: 'Governance',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Multi-Modal Ingestion',
        description: 'Invoices, shipping notices, or customer tickets arrive via email, API, or EDI and are parsed into normalized vector states.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Semantic Validation & Policy Check',
        description: 'Autonomous agents cross-reference purchase orders against warehouse inventory ledgers and enterprise pricing schedules.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Two-Phase ERP Commit',
        description: 'The system generates validated GL accounting entries and submits them to the ERP system under strict idempotency.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Audit Confirmation & Dispatch',
        description: 'Downstream notifications are sent to vendors and internal stakeholders with complete cryptographic audit references.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Global supply chain operators managing multi-region purchase orders.',
      'Healthcare provider networks adjudicating claims and patient intake.',
      'Financial institutions reconciling multi-currency ledger transactions.',
      'Enterprises with 200+ employees managing cross-department operational sprawl.',
    ],
    industries: ['healthcare', 'financial-services', 'b2b-sales'],
    relatedTechnology: ['automation', 'ai-agents', 'software'],
    relatedProducts: ['model-010', 'event-mesh-runtime'],
    relatedCaseStudies: ['autonomous-claims-orchestration', 'global-treasury-reconciliation'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Discuss Operational Automation',
    seo: {
      title: 'Autonomous Business Operations & Workflow Automation | NexAgent Solutions',
      description: 'End-to-end enterprise workflow automation connecting AI agents with legacy ERP, CRM, and accounting mainframes with deterministic safety.',
      canonicalUrl: 'https://nexagent.group/solutions/business-automation',
    },
  },
  {
    id: 'sol-sales-automation',
    slug: 'sales-automation',
    name: 'Autonomous Revenue Operations & Pipeline Intelligence',
    category: 'Operations',
    summary: 'Autonomous sales engagement runtimes that research prospect accounts, synthesize executive briefs, conduct voice follow-ups, and keep CRMs continuously updated.',
    problem: 'Enterprise sales representatives spend less than 35% of their working hours actually selling. The remainder is consumed by manual CRM data entry, manual prospect research, meeting note formatting, and missed follow-up windows.',
    traditionalBreakdown: [
      'Generic email sequencers blast low-conversion spam, damaging corporate domain reputation.',
      'Manual CRM updating leads to inaccurate pipeline forecasting and missed deals.',
      'Valuable customer call insights remain trapped in siloed meeting recordings.',
      'SDR turnover and retraining costs drain executive bandwidth and revenue momentum.',
    ],
    approach: 'NexAgent deploys an autonomous revenue engine that listens to sales interactions, performs deep multi-source company research, drafts contextual follow-ups within minutes of call conclusion, and auto-updates CRM deal stages with complete buyer signals.',
    systemComponents: [
      {
        name: 'Real-Time Conversation Streamer',
        description: 'Zero-latency audio and transcription pipe capturing buyer sentiment, budget mentions, and competitor benchmarks.',
        badge: 'Perception',
      },
      {
        name: 'Account Signal Synthesizer',
        description: 'Agents querying financial filings, LinkedIn, and tech-stack trackers to build comprehensive prospect dossier cards.',
        badge: 'Intelligence',
      },
      {
        name: 'Bi-Directional CRM Sync Engine',
        description: 'Automated field updating for Salesforce and HubSpot ensuring 100% pipeline accuracy with zero manual logging.',
        badge: 'Integration',
      },
      {
        name: 'Contextual Action Dispatcher',
        description: 'Generates tailored follow-up technical proposals, security documents, and scheduling links personalized to buyer questions.',
        badge: 'Execution',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Target Account Intelligence',
        description: 'Autonomous agents continuously ingest hiring signals, technology changes, and news to identify verified enterprise buying windows.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Contextual Inbound Qualification',
        description: 'Inbound requests are matched against ICP criteria, enriched with corporate metadata, and assigned a qualification score.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Meeting Synthesis & CRM Update',
        description: 'Call transcripts are parsed for buyer objections, next steps, and budget timelines, synchronizing directly into deal stages.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Automated Stakeholder Follow-Up',
        description: 'Tailored technical summaries and requested collateral are prepared and staged for executive review and transmission.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'B2B Enterprise Software and SaaS companies with 10+ account executives.',
      'Professional services and consulting firms with complex consultative sales cycles.',
      'Commercial real estate and private equity advisory groups.',
    ],
    industries: ['b2b-sales', 'hospitality'],
    relatedTechnology: ['ai-agents', 'voice-ai', 'automation'],
    relatedProducts: ['model-010'],
    relatedCaseStudies: ['distributed-guest-voice-mesh'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Accelerate Revenue Operations',
    seo: {
      title: 'Autonomous Sales Automation & Pipeline Intelligence | NexAgent Solutions',
      description: 'Streamline B2B sales cycles with autonomous account research, real-time meeting synthesis, and bi-directional CRM deal state synchronization.',
      canonicalUrl: 'https://nexagent.group/solutions/sales-automation',
    },
  },
  {
    id: 'sol-documentation-automation',
    slug: 'documentation-automation',
    name: 'Ambient Documentation & Regulatory Compliance Generation',
    category: 'Intelligence',
    summary: 'Ambient audio and workflow listening systems that automatically generate clinical charts, legal briefs, and compliance reports with strict terminology enforcement.',
    problem: 'Physicians, attorneys, and compliance officers spend up to 4 hours per day compiling mandatory clinical notes, case filings, and regulatory audit summaries. Administrative burnout is at an all-time high across licensed professions.',
    traditionalBreakdown: [
      'Dictation tools produce raw, unstructured transcripts that require extensive manual editing.',
      'Legacy templates fail to adapt to specialized medical sub-specialties or legal jurisdictions.',
      'Copy-paste charting creates compliance vulnerabilities and billing audit clawbacks.',
      'Physicians spend more time looking at computer screens than interacting directly with patients.',
    ],
    approach: 'NexAgent ambient systems capture natural spoken encounters in the background, extract clinical or legal facts into specialized ontology trees (SNOMED, ICD-10, FHIR), and draft fully compliant documentation ready for clinician review and signature.',
    systemComponents: [
      {
        name: 'Ambient Acoustic Sensor Engine',
        description: 'Far-field microphone processing separating multi-party doctor-patient or attorney-client dialogue with acoustic noise gating.',
        badge: 'Acoustics',
      },
      {
        name: 'Domain Ontology Parser',
        description: 'Specialized medical and legal language models mapping spoken idioms to standardized clinical and statutory codes.',
        badge: 'Intelligence',
      },
      {
        name: 'EHR / DMS Direct Injector',
        description: 'FHIR-compliant and document management connectors injecting finalized notes directly into Epic, Cerner, or iManage.',
        badge: 'Integration',
      },
      {
        name: 'Compliance Attestation Cryptography',
        description: 'Immutable digital signature verification and audit logging ensuring HIPAA and legal privilege preservation.',
        badge: 'Security',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Ambient Encounter Capture',
        description: 'During patient consultations or legal client meetings, dialogue is streamed over encrypted, zero-egress audio pipelines.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Ontology Entity Extraction',
        description: 'Symptoms, diagnoses, lab orders, and legal statutes are parsed into structured FHIR or legal document schemas.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Automated Note Synthesis',
        description: 'A comprehensive SOAP note or legal case summary is synthesized in the exact institutional style required.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'One-Click Review & EHR Sync',
        description: 'The practitioner reviews the generated brief, applies digital signature, and the record commits instantly to the EHR.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Hospital networks, clinical practices, and outpatient surgical centers.',
      'Enterprise legal departments and commercial law firms.',
      'Financial compliance and anti-money laundering (AML) auditing groups.',
    ],
    industries: ['healthcare', 'financial-services'],
    relatedTechnology: ['voice-ai', 'ai-agents', 'software'],
    relatedProducts: ['model-010'],
    relatedCaseStudies: ['autonomous-claims-orchestration'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Deploy Ambient Documentation',
    seo: {
      title: 'Ambient Documentation & Regulatory Compliance Automation | NexAgent Solutions',
      description: 'Automate clinical charting, legal briefs, and compliance reports with ambient voice listening, domain ontology mapping, and direct EHR integration.',
      canonicalUrl: 'https://nexagent.group/solutions/documentation-automation',
    },
  },
  {
    id: 'sol-crm-systems',
    slug: 'crm-systems',
    name: 'Autonomous CRM Engines & Bi-Directional State Mesh',
    category: 'Integration',
    summary: 'Autonomous customer data platform that unifies fragmented sales, billing, and support records into a single real-time operational state machine.',
    problem: 'Enterprise customer data is scattered across Salesforce, Zendesk, Stripe, HubSpot, and ERP warehouses. Inconsistent records cause billing mistakes, duplicate sales touches, and inaccurate executive reporting.',
    traditionalBreakdown: [
      'Batch nightly sync scripts leave teams operating on 24-hour stale customer data.',
      'Manual record de-duplication is slow, expensive, and prone to human error.',
      'Support teams have no visibility into current sales negotiations or contract renewals.',
      'SaaS per-seat fees skyrocket while data quality deteriorates year over year.',
    ],
    approach: 'NexAgent builds event-driven state synchronization meshes. Any customer touchpoint—a support ticket, billing payment, or signed contract—propagates instantly across all connected systems with automatic record deduplication and resolution.',
    systemComponents: [
      {
        name: 'Event Stream Ingress',
        description: 'Sub-millisecond gRPC and webhook listeners ingesting state transitions from all enterprise touchpoints.',
        badge: 'Ingress',
      },
      {
        name: 'Entity Resolution Arbiter',
        description: 'Probabilistic and deterministic matching algorithms merging disparate records into a unified golden customer profile.',
        badge: 'Intelligence',
      },
      {
        name: 'State Synchronization Mesh',
        description: 'Bi-directional transaction dispatch updating downstream CRMs, ERPs, and billing engines concurrently.',
        badge: 'Integration',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Event Detection',
        description: 'A transaction or communication event occurs across any connected tool or communication channel.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Autonomous Entity Matching',
        description: 'The engine resolves domain, tax ID, and contact details to ensure zero duplicate records are created.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Multi-System State Update',
        description: 'Customer status, active ARR, and support tier update across all systems within 150ms.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Proactive Alerting',
        description: 'Executive stakeholders receive automated alerts on key account milestones or churn risk triggers.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Multi-entity enterprise holdings and conglomerate subsidiaries.',
      'High-growth tech companies with multi-product customer portfolios.',
      'Financial services groups with stringent customer KYC and audit requirements.',
    ],
    industries: ['b2b-sales', 'financial-services', 'hospitality'],
    relatedTechnology: ['automation', 'software'],
    relatedProducts: ['event-mesh-runtime'],
    relatedCaseStudies: ['global-treasury-reconciliation'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Unify Customer Systems',
    seo: {
      title: 'Autonomous CRM Engines & Bi-Directional State Mesh | NexAgent Solutions',
      description: 'Unify fragmented enterprise customer data into a real-time state machine with autonomous entity resolution and instant bi-directional CRM synchronization.',
      canonicalUrl: 'https://nexagent.group/solutions/crm-systems',
    },
  },
];
