import { SolutionItem } from './types';

export const solutions: SolutionItem[] = [
  {
    id: 'sol-business-automation',
    slug: 'business-automation',
    name: 'Autonomous Business Operations & Workflow Automation',
    category: 'Automation',
    summary: 'End-to-end enterprise workflow automation replacing manual data re-entry, invoice reconciliation, and cross-department routing with autonomous agent coordination.',
    problem: 'Enterprise departments waste thousands of skilled labor hours copying data across disparate ERPs, CRMs, spreadsheets, and ticketing portals. Human routing introduces delays, transcription errors, and operational bottlenecks.',
    traditionalBreakdown: [
      'Fragile point-to-point Zapier/Make automations break whenever an API schema changes.',
      'RPA screen-scraping bots fail when UI layouts shift by a single pixel.',
      'Manual verification creates 48–72 hour delays in transaction settlement and approvals.',
      'Zero auditable context remains when automated scripts produce incorrect downstream records.',
    ],
    approach: 'NexAgent replaces brittle script-based automation with cognitive multi-agent workflows. Our systems understand semantic document structure, validate business rules using Model-010 reasoning, and execute two-phase commit transactions into backend enterprise databases with immutable audit logs.',
    systemComponents: [
      {
        name: 'Autonomous Perception Layer',
        description: 'Multi-modal document and event parsers converting PDFs, emails, invoices, and EDI feeds into structured JSON schemas.',
        badge: 'Ingress',
      },
      {
        name: 'Model-010 Consensus Engine',
        description: 'Multi-agent arbitration checking contract clauses, pricing schedules, and regulatory bounds before approving actions.',
        badge: 'Intelligence',
      },
      {
        name: 'Two-Phase Commit Dispatcher',
        description: 'Idempotent transactional gateway committing records simultaneously across SAP, Oracle, and Salesforce with instant rollback.',
        badge: 'Automation',
      },
      {
        name: 'Immutable Audit Ledger',
        description: 'Cryptographic time-stamped record of all prompts, reasoning steps, tool executions, and database responses.',
        badge: 'Governance',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Multi-Modal Ingestion',
        description: 'Invoices, shipping notices, or customer tickets arrive via email, API, or EDI and are parsed into normalized vector states.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Semantic Validation & Policy Check',
        description: 'Autonomous agents cross-reference purchase orders against warehouse inventory ledgers and enterprise pricing schedules.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Two-Phase ERP Commit',
        description: 'The system generates validated GL accounting entries and submits them to the ERP system under strict idempotency.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Audit Confirmation & Dispatch',
        description: 'Downstream notifications are sent to vendors and internal stakeholders with complete cryptographic audit references.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Global supply chain operators managing multi-region purchase orders.',
      'Healthcare provider networks adjudicating claims and patient intake.',
      'Financial institutions reconciling multi-currency ledger transactions.',
      'Enterprises with 200+ employees managing cross-department operational sprawl.',
    ],
    industries: ['healthcare', 'financial-services', 'b2b-sales'],
    relatedTechnology: ['automation', 'ai-agents', 'software'],
    relatedProducts: ['model-010', 'event-mesh-runtime'],
    relatedCaseStudies: ['autonomous-claims-orchestration', 'global-treasury-reconciliation'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Discuss Operational Automation',
    seo: {
      title: 'Autonomous Business Operations & Workflow Automation | NexAgent Solutions',
      description: 'End-to-end enterprise workflow automation connecting AI agents with legacy ERP, CRM, and accounting mainframes with deterministic safety.',
      canonicalUrl: 'https://nexagent.group/solutions/business-automation',
    },
  },
  {
    id: 'sol-sales-automation',
    slug: 'sales-automation',
    name: 'Autonomous Revenue Operations & Pipeline Intelligence',
    category: 'Operations',
    summary: 'Autonomous sales engagement runtimes that research prospect accounts, synthesize executive briefs, conduct voice follow-ups, and keep CRMs continuously updated.',
    problem: 'Enterprise sales representatives spend less than 35% of their working hours actually selling. The remainder is consumed by manual CRM data entry, manual prospect research, meeting note formatting, and missed follow-up windows.',
    traditionalBreakdown: [
      'Generic email sequencers blast low-conversion spam, damaging corporate domain reputation.',
      'Manual CRM updating leads to inaccurate pipeline forecasting and missed deals.',
      'Valuable customer call insights remain trapped in siloed meeting recordings.',
      'SDR turnover and retraining costs drain executive bandwidth and revenue momentum.',
    ],
    approach: 'NexAgent deploys an autonomous revenue engine that listens to sales interactions, performs deep multi-source company research, drafts contextual follow-ups within minutes of call conclusion, and auto-updates CRM deal stages with complete buyer signals.',
    systemComponents: [
      {
        name: 'Telephony & Meeting Ingress',
        description: 'Zero-latency audio and transcription pipe capturing buyer sentiment, budget mentions, and competitor benchmarks.',
        badge: 'Ingress',
      },
      {
        name: 'Account Intelligence Engine',
        description: 'Autonomous research agents crawling corporate filings, hiring trends, and tech stacks to build actionable dossiers.',
        badge: 'Intelligence',
      },
      {
        name: 'CRM Auto-Reconciliation Bus',
        description: 'Bi-directional synchronization layer updating Salesforce and HubSpot opportunities, contacts, and stages in real time.',
        badge: 'Integration',
      },
      {
        name: 'Executive Follow-Up Synthesizer',
        description: 'Context-aware drafting engine generating personalized proposal briefs and follow-up emails tailored to executive buyers.',
        badge: 'Automation',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Inbound Signal Capture',
        description: 'Lead signs up or requests information; autonomous agent immediately aggregates firmographic data and buyer intent.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Dossier & Opportunity Scoring',
        description: 'The system computes qualification score, identifies key economic buyers, and generates tailored meeting briefs for the rep.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Autonomous Post-Call Synthesis',
        description: 'Call transcripts are parsed for buyer objections, next steps, and budget timelines, synchronizing directly into deal stages.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Deterministic CRM Sync',
        description: 'Deal stages, next steps, and contact notes are committed to Salesforce under verified schema invariants.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'High-growth B2B SaaS companies scaling sales team headcount.',
      'Enterprise advisory and professional service partnerships.',
      'Commercial real estate and private equity transaction groups.',
      'Sales teams managing complex multi-stakeholder deal cycles.',
    ],
    industries: ['b2b-sales', 'financial-services'],
    relatedTechnology: ['ai-agents', 'voice-ai', 'software'],
    relatedProducts: ['model-010'],
    relatedCaseStudies: ['high-growth-fintech-underwriting'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Deploy Revenue Automation',
    seo: {
      title: 'Autonomous Revenue Operations & Pipeline Intelligence | NexAgent Solutions',
      description: 'Streamline enterprise sales pipeline with autonomous prospect research, intelligent CRM auto-sync, and automated post-call meeting synthesis.',
      canonicalUrl: 'https://nexagent.group/solutions/sales-automation',
    },
  },
  {
    id: 'sol-marketing-automation',
    slug: 'marketing-automation',
    name: 'Autonomous Marketing Workflows & Lifecycle Engines',
    category: 'Operations',
    summary: 'Streamline multi-channel content distribution, behavioral audience segmentation, and lead attribution without manual campaign overhead.',
    problem: 'Marketing teams spend endless cycles manually reformatting copy for five different social channels, configuring complex email workflows, and wrestling with disconnected campaign attribution spreadsheets.',
    traditionalBreakdown: [
      'Manual multi-channel publishing causes inconsistent messaging and missed campaign deadlines.',
      'Static email drips fail to adapt dynamically to real-time prospect browsing behavior.',
      'First-touch and multi-touch attribution data is fragmented across Google, LinkedIn, and CRM silos.',
      'Creative assets take weeks to iterate due to slow departmental feedback loops.',
    ],
    approach: 'NexAgent builds autonomous marketing engines that monitor user signals, generate on-brand cross-channel campaign variations, trigger behavioral communications, and attribute conversion ROI directly back to pipeline revenue.',
    systemComponents: [
      {
        name: 'Behavioral Signal Collector',
        description: 'Real-time event stream tracking user journeys, content engagement, and product telemetry.',
        badge: 'Ingress',
      },
      {
        name: 'Creative Adaptation Engine',
        description: 'Model-010 driven copy and asset adaptation maintaining exact brand voice across all touchpoints.',
        badge: 'Intelligence',
      },
      {
        name: 'Multi-Channel Dispatch Hub',
        description: 'Automated publishing connectors for email, LinkedIn, web personalization, and CMS.',
        badge: 'Automation',
      },
      {
        name: 'Revenue Attribution Ledger',
        description: 'Deterministic cross-channel touchpoint attribution calculating verified customer acquisition cost and ROI.',
        badge: 'Analytics',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Signal Collection & Tracking',
        description: 'Prospects interact across web, content assets, or product demos, generating high-intent behavioral events.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Dynamic Audience Segmentation',
        description: 'Autonomous rules group prospects into precise lifecycle tiers based on velocity and content engagement.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Personalized Campaign Triggering',
        description: 'Tailored email briefs, product walkthroughs, and case study excerpts are dispatched automatically.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Pipeline Attribution Reconciliation',
        description: 'Every interaction is logged against the CRM opportunity, providing clear attribution for marketing spend.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'High-velocity marketing teams managing cross-channel customer funnels.',
      'E-commerce brands orchestrating personalized lifecycle retention.',
      'B2B tech companies running account-based marketing (ABM) programs.',
      'Media and content organizations automating publishing workflows.',
    ],
    industries: ['b2b-sales', 'hospitality'],
    relatedTechnology: ['automation', 'software'],
    relatedProducts: ['event-mesh-runtime'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Automate Marketing Engines',
    seo: {
      title: 'Autonomous Marketing Workflows & Lifecycle Engines | NexAgent Solutions',
      description: 'Streamline multi-channel publishing, behavioral lifecycle personalization, and cross-channel revenue attribution with NexAgent marketing automation.',
      canonicalUrl: 'https://nexagent.group/solutions/marketing-automation',
    },
  },
  {
    id: 'sol-ai-assistants',
    slug: 'ai-assistants',
    name: 'Omnichannel AI Customer Communication & Resolution',
    category: 'Intelligence',
    summary: 'Instant, accurate, 24/7 customer assistance across web, email, WhatsApp, and SMS that directly executes transactions and resolves complex customer tickets.',
    problem: 'Support teams are buried under repetitive customer inquiries regarding order status, booking modifications, refunds, and troubleshooting. Customer wait times surge during peak hours, degrading satisfaction and retention.',
    traditionalBreakdown: [
      'Legacy keyword chatbots misunderstand queries and frustrate customers with endless loops.',
      'Human support agents spend half their day searching internal documentation for answers.',
      'Tier 1 support costs scale linearly with customer volume, eroding operating margins.',
      'After-hours customer inquiries sit unanswered for 12 to 24 hours, causing churn.',
    ],
    approach: 'NexAgent builds domain-specific conversational AI agents grounded in your live databases and company policies. Our agents don’t just converse—they safely call APIs to look up orders, update reservations, process exchanges, and escalate edge cases with full context.',
    systemComponents: [
      {
        name: 'Omnichannel Ingress Gateway',
        description: 'Unified message bus ingesting web chat, email, SMS, and WhatsApp conversations with sub-100ms response.',
        badge: 'Ingress',
      },
      {
        name: 'Knowledge Retrieval & Policy Engine',
        description: 'Semantic vector index over company SOPs, refund rules, product manuals, and FAQs.',
        badge: 'Intelligence',
      },
      {
        name: 'Transactional API Executor',
        description: 'Sandboxed tool callers that read and write directly to Zendesk, Shopify, Stripe, and internal databases.',
        badge: 'Automation',
      },
      {
        name: 'Human Hand-Off Orchestrator',
        description: 'Seamless escalation to human agents with comprehensive summaries and recommended response drafts.',
        badge: 'Operations',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Customer Inquiry Ingress',
        description: 'A customer reaches out via web chat or messaging with an urgent request or technical question.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Intent Classification & Policy Verification',
        description: 'The AI classifies intent, checks customer account status, and retrieves applicable corporate policies.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Direct Transaction Execution',
        description: 'The agent issues verified API calls to update records, schedule appointments, or reissue credentials.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Customer Satisfaction Confirmation',
        description: 'The resolution is confirmed with the customer, and the full transcript and audit logs are saved to CRM.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'E-commerce brands handling high volumes of order tracking and returns.',
      'SaaS platforms needing 24/7 technical troubleshooting support.',
      'Hospitality, travel, and logistics operators with round-the-clock booking needs.',
      'Service companies aiming to improve response times from hours to seconds.',
    ],
    industries: ['hospitality', 'b2b-sales', 'healthcare'],
    relatedTechnology: ['ai-agents', 'voice-ai', 'software'],
    relatedProducts: ['model-010'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Deploy AI Customer Assistants',
    seo: {
      title: 'Omnichannel AI Customer Communication | NexAgent Solutions',
      description: '24/7 autonomous customer communication across web chat, WhatsApp, and email that solves inquiries directly through live database connections.',
      canonicalUrl: 'https://nexagent.group/solutions/ai-assistants',
    },
  },
  {
    id: 'sol-voice-ai',
    slug: 'voice-ai',
    name: 'Ultra-Low Latency Conversational Voice Agents',
    category: 'Intelligence',
    summary: 'Sub-200ms conversational turn-taking telephony agents that answer incoming calls, conduct outbound follow-ups, book appointments, and route urgent escalations.',
    problem: 'Businesses miss thousands of telephone calls every month due to staff shortages, long hold queues, and closed office hours. Every abandoned call is a lost customer, delayed appointment, or damaged reputation.',
    traditionalBreakdown: [
      'Robotic IVR phone trees frustrate callers with endless number-punching menus.',
      'Third-party answering services lack deep product knowledge and misclassify urgent issues.',
      'High call abandonment rates during peak volume drive prospects directly to competitors.',
      'Full-time call center staffing across multiple time zones creates severe overhead.',
    ],
    approach: 'NexAgent engineers speech-to-speech voice runtimes with sub-200ms round-trip latency. Our voice agents listen naturally, understand tone, handle human interruptions smoothly, and integrate directly into your telephony PBX and CRM databases.',
    systemComponents: [
      {
        name: 'WebRTC Telephony SIP Trunk',
        description: 'Ultra-low latency SIP connector directly interfaced with Twilio, Asterisk, and carrier networks.',
        badge: 'Ingress',
      },
      {
        name: 'Streaming Speech-to-Speech Core',
        description: 'Zero-buffer neural acoustic tokenizer translating speech with human cadence and natural pauses.',
        badge: 'Intelligence',
      },
      {
        name: 'Live Calendar & Database Connector',
        description: 'Deterministic API callers querying availability, booking appointments, and confirming reservations.',
        badge: 'Automation',
      },
      {
        name: 'Call Transcript & Summary Engine',
        description: 'Instant call audio recording, transcription, sentiment tagging, and post-call CRM sync.',
        badge: 'Analytics',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Inbound Call Ring',
        description: 'The telephone call is answered within one ring over an encrypted WebRTC audio stream.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Natural Conversation & Intent Parsing',
        description: 'The caller speaks naturally; the agent understands complex questions, accents, and interruptions.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Live Database Booking & Action',
        description: 'The agent checks real-time slot availability, books the calendar, and sends an instant SMS confirmation.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Summary Archival & CRM Dispatch',
        description: 'Call recording and AI summary are automatically pushed to the customer record for staff review.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Medical clinics, dental offices, and wellness practices managing appointment bookings.',
      'Luxury hospitality, resorts, and fine dining establishments taking reservations.',
      'Home services and emergency contractor dispatch lines.',
      'Automotive dealerships and service centers handling service inquiries.',
    ],
    industries: ['healthcare', 'hospitality'],
    relatedTechnology: ['voice-ai', 'ai-agents'],
    relatedProducts: ['model-010'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Deploy Conversational Voice AI',
    seo: {
      title: 'Conversational Voice AI & Autonomous Telephony | NexAgent Solutions',
      description: 'Sub-200ms conversational turn-taking voice agents for enterprise telephone booking, inquiry handling, and automated dispatch.',
      canonicalUrl: 'https://nexagent.group/solutions/voice-ai',
    },
  },
  {
    id: 'sol-ai-agents',
    slug: 'ai-agents',
    name: 'Enterprise Knowledge Assistants & Cognitive Workers',
    category: 'Intelligence',
    summary: 'Deploy specialized internal AI assistants securely connected to your proprietary documents, databases, SOPs, and communications to multiply employee productivity.',
    problem: 'Knowledge workers spend up to 20% of their working hours searching for internal information, reconciling conflicting document versions, and answering repetitive internal questions.',
    traditionalBreakdown: [
      'Generic consumer AI chatbots hallucinate citations and leak confidential corporate IP.',
      'Internal wikis and Notion databases rapidly become outdated, fragmented, and unsearchable.',
      'Onboarding new employees takes months due to institutional knowledge being locked in senior staff heads.',
      'Lack of role-based security means sensitive financial and HR records risk unauthorized exposure.',
    ],
    approach: 'NexAgent designs private, role-governed enterprise AI assistants with strict citation guarantees. Connected directly to your Google Drive, Slack, GitHub, Jira, and SQL databases, our agents synthesize verified answers with clickable document sources.',
    systemComponents: [
      {
        name: 'Enterprise Data Ingestion Pipeline',
        description: 'Incremental document indexing across Google Drive, Notion, Confluence, Slack, and codebases.',
        badge: 'Ingress',
      },
      {
        name: 'Strict Citation RAG Engine',
        description: 'Hybrid semantic and keyword search engine that answers only using verified internal source citations.',
        badge: 'Intelligence',
      },
      {
        name: 'Role-Based Access Control (RBAC)',
        description: 'Zero-trust permission fences ensuring users only see information authorized for their clearance level.',
        badge: 'Governance',
      },
      {
        name: 'Slack & Teams Native Bot',
        description: 'Frictionless collaboration bot living directly where your team already communicates daily.',
        badge: 'Integration',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Query Ingress via Slack or Web',
        description: 'An employee asks a complex question regarding company policy, client history, or technical architecture.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Permission Check & Vector Retrieval',
        description: 'The system validates user access rights and retrieves the most relevant canonical source passages.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Synthesized Answer with Citations',
        description: 'The assistant delivers a precise, concise answer with clickable links to the exact paragraphs cited.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Audit Trail & Knowledge Gap Detection',
        description: 'Unanswered questions are flagged for leadership, highlighting missing or outdated company documentation.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Engineering and product teams navigating extensive codebases and technical documentation.',
      'Law firms and compliance departments managing thousands of legal filings and contracts.',
      'Growing companies looking to accelerate new employee onboarding.',
      'Enterprises with strict data sovereignty and security governance mandates.',
    ],
    industries: ['financial-services', 'healthcare', 'b2b-sales'],
    relatedTechnology: ['ai-agents', 'software'],
    relatedProducts: ['model-010'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Build Enterprise AI Assistants',
    seo: {
      title: 'Enterprise Knowledge Assistants & Cognitive Workers | NexAgent Solutions',
      description: 'Private, secure internal AI assistants connected to your proprietary SOPs, docs, and databases with role-based access control and strict citation guarantees.',
      canonicalUrl: 'https://nexagent.group/solutions/ai-agents',
    },
  },
  {
    id: 'sol-modernize-software',
    slug: 'modernize-software',
    name: 'Legacy Software Modernization & Cloud Platforms',
    category: 'Automation',
    summary: 'Re-engineer outdated legacy portals, spreadsheets, and brittle internal tools into high-velocity, modern web applications built for reliability and scale.',
    problem: 'Companies operate on legacy software built a decade ago or critical workflows taped together with messy Excel spreadsheets. These systems are slow, insecure, unable to integrate with modern APIs, and impossible to access on mobile.',
    traditionalBreakdown: [
      'Legacy software vendor lock-in with exorbitant maintenance contracts and zero new features.',
      'Spreadsheet corruption and accidental formula overwrites causing costly operational mistakes.',
      'Clunky user interfaces require weeks of employee training and cause high user frustration.',
      'Inability to scale infrastructure to meet modern transaction loads and cybersecurity standards.',
    ],
    approach: 'NexAgent builds modern, responsive, cloud-native web applications using Next.js, Node, Go, and PostgreSQL. We migrate your legacy databases cleanly, design elegant intuitive interfaces, and deliver clean, well-documented codebases you fully own.',
    systemComponents: [
      {
        name: 'Legacy Data Migration Pipeline',
        description: 'Zero-downtime ETL pipelines migrating legacy SQL/Access databases into modern relational schemas.',
        badge: 'Ingress',
      },
      {
        name: 'High-Performance Next.js Architecture',
        description: 'Server-rendered, ultra-fast web interfaces built with modern component design systems.',
        badge: 'Frontend',
      },
      {
        name: 'Secure API & Microservices Core',
        description: 'Type-safe REST and GraphQL APIs with robust role management, OAuth2, and rate limiting.',
        badge: 'Backend',
      },
      {
        name: 'Automated CI/CD & Cloud Infrastructure',
        description: 'Production infrastructure on AWS/Vercel with automated testing, monitoring, and daily backups.',
        badge: 'DevOps',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Legacy Architecture Audit',
        description: 'We analyze your existing workflows, database schemas, and integration points to identify bottlenecks.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'UX Design & Modern Schema Architecture',
        description: 'We design intuitive, ergonomic interfaces and structure clean normalized database architectures.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Full-Stack Development & Migration',
        description: 'We engineer the modern application with comprehensive automated testing and zero data loss migration.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Production Deployment & Handoff',
        description: 'The platform launches into live production with monitoring, complete documentation, and team training.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Businesses outgrowing multi-tab spreadsheets and manual desktop software.',
      'Enterprises held hostage by slow, overpriced legacy software providers.',
      'Operations teams requiring bespoke internal control portals and dashboards.',
      'Companies wanting complete code ownership without recurring per-seat SaaS fees.',
    ],
    industries: ['b2b-sales', 'hospitality', 'financial-services'],
    relatedTechnology: ['software', 'automation'],
    relatedProducts: ['event-mesh-runtime'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Modernize Your Software',
    seo: {
      title: 'Legacy Software Modernization & Cloud Platforms | NexAgent Solutions',
      description: 'Re-engineer outdated legacy software, spreadsheets, and portals into modern, high-velocity cloud web applications you fully own.',
      canonicalUrl: 'https://nexagent.group/solutions/modernize-software',
    },
  },
  {
    id: 'sol-crm-and-business-systems',
    slug: 'crm-and-business-systems',
    name: 'System Integration, API Middleware & ERP Connectors',
    category: 'Integration',
    summary: 'Build robust bi-directional integration bridges connecting your ERP, CRM, accounting tools, e-commerce platforms, and legacy databases into a unified real-time data mesh.',
    problem: 'Every department in a modern company uses different software: Sales uses Salesforce, Support uses Zendesk, Accounting uses QuickBooks or NetSuite, and Operations uses custom databases. Data silos prevent cross-functional collaboration and real-time visibility.',
    traditionalBreakdown: [
      'Brittle Zapier or webhook scripts fail silently, creating mismatched inventory and billing errors.',
      'Nightly batch sync jobs mean decisions are made on 24-hour outdated operational metrics.',
      'Employees spend hours manually re-entering records from one software tool into another.',
      'Custom point-to-point integrations become an unmaintainable nightmare of tangled code.',
    ],
    approach: 'NexAgent engineers enterprise-grade integration middleware with idempotent message queues, automated schema translation, and two-phase commit guarantees. Any update in one system propagates reliably across all connected platforms in real time.',
    systemComponents: [
      {
        name: 'Event Stream & Webhook Ingress',
        description: 'High-throughput event broker receiving state changes via webhooks, CDC, and REST APIs.',
        badge: 'Ingress',
      },
      {
        name: 'Schema Mapping & Transformation Arbiter',
        description: 'Automated data normalization translating differing entity formats across platforms.',
        badge: 'Intelligence',
      },
      {
        name: 'Idempotent Transaction Dispatcher',
        description: 'Guaranteed-delivery queues with automatic retries, dead-letter monitoring, and rollback.',
        badge: 'Integration',
      },
      {
        name: 'Real-Time Health & Alert Dashboard',
        description: 'Comprehensive telemetry monitoring API latency, sync health, and webhook delivery status.',
        badge: 'Monitoring',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Trigger Event Ingress',
        description: 'A new deal closes in the CRM or a payment succeeds in Stripe, generating an immediate event payload.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Schema Normalization & Deduplication',
        description: 'The middleware maps customer IDs, formats currencies, and verifies entity resolution rules.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Bi-Directional Multi-System Dispatch',
        description: 'ERP invoices, warehouse fulfillment orders, and provisioning accounts are updated in parallel.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Delivery Verification & Audit Trail',
        description: 'Every transaction is confirmed with cryptographic timestamps and stored in a searchable audit log.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Companies with 5+ disparate software tools that need to speak seamlessly to each other.',
      'Enterprises integrating acquisitions or multiple subsidiary databases.',
      'E-commerce operations coordinating multi-warehouse inventory and accounting.',
      'Organizations requiring real-time data flow without manual data entry staff.',
    ],
    industries: ['b2b-sales', 'financial-services', 'hospitality'],
    relatedTechnology: ['automation', 'software'],
    relatedProducts: ['event-mesh-runtime'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Connect Your Systems',
    seo: {
      title: 'System Integration, API Middleware & ERP Connectors | NexAgent Solutions',
      description: 'Connect enterprise CRM, ERP, billing, and database systems with reliable, real-time bi-directional integration middleware and zero-loss guarantees.',
      canonicalUrl: 'https://nexagent.group/solutions/crm-and-business-systems',
    },
  },
  {
    id: 'sol-business-intelligence',
    slug: 'business-intelligence',
    name: 'Business Intelligence, Real-Time Dashboards & Anomaly Detection',
    category: 'Operations',
    summary: 'Transform scattered business records into interactive executive dashboards, automated anomaly alerts, and scheduled operational intelligence reports.',
    problem: 'Business leaders struggle to get an accurate view of company health because metrics are scattered across spreadsheets, billing processors, ad platforms, and CRM databases. Generating monthly reports takes days of manual aggregation.',
    traditionalBreakdown: [
      'Static monthly PDF reports arrive weeks too late for executives to make timely course corrections.',
      'Spreadsheets with manual formulas introduce silent calculation errors that mislead leadership.',
      'Complex enterprise BI tools (PowerBI, Tableau) require expensive specialist consultants to configure.',
      'Critical revenue anomalies, churn spikes, or inventory shortages are noticed only after damage is done.',
    ],
    approach: 'NexAgent builds real-time business intelligence pipelines that unify your operational data, run automated anomaly detection algorithms, and present actionable metrics in sleek, high-velocity executive dashboards tailored to your KPIs.',
    systemComponents: [
      {
        name: 'Unified Data Warehouse Ingress',
        description: 'Automated connectors streaming data from Stripe, PostgreSQL, Salesforce, and ad accounts.',
        badge: 'Ingress',
      },
      {
        name: 'Statistical Anomaly Detection Engine',
        description: 'Algorithms continuously monitoring metric baselines to detect drop-offs or surges instantly.',
        badge: 'Intelligence',
      },
      {
        name: 'Executive KPI Visualizer',
        description: 'Lightning-fast, interactive charts and cohort retention graphs with zero loading latency.',
        badge: 'Frontend',
      },
      {
        name: 'Automated Briefing Bot',
        description: 'Scheduled weekly or monthly executive summaries delivered directly to email or Slack.',
        badge: 'Automation',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Continuous Metric Streaming',
        description: 'Revenue, orders, customer acquisition, and operational throughput stream into a clean analytics store.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Metric Aggregation & Benchmark Analysis',
        description: 'Data is aggregated into actionable KPIs, comparing current performance against trailing baselines.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Dashboard Refresh & Alert Dispatch',
        description: 'Dashboards update in real time; if an anomalous trend is detected, an alert is triggered to leadership.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Scheduled Executive Synthesis',
        description: 'Every Monday morning, a synthesized operational brief is sent to executive leadership with key insights.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Founders and CEOs seeking instant visibility into cash flow, revenue, and churn.',
      'Operations directors monitoring supply chain throughput and fulfillment velocity.',
      'Finance teams wanting automated GAAP revenue reconciliation and cohort metrics.',
      'Fast-growing businesses wanting clarity without hiring a dedicated data engineering team.',
    ],
    industries: ['financial-services', 'b2b-sales', 'hospitality'],
    relatedTechnology: ['software', 'automation'],
    relatedProducts: ['model-010'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Build Business Intelligence',
    seo: {
      title: 'Business Intelligence & Real-Time Dashboards | NexAgent Solutions',
      description: 'Transform enterprise data into live interactive executive dashboards, automated anomaly detection alerts, and scheduled operational reports.',
      canonicalUrl: 'https://nexagent.group/solutions/business-intelligence',
    },
  },
  {
    id: 'sol-documentation-automation',
    slug: 'documentation-automation',
    name: 'Intelligent Document Extraction & Autonomous Compliance',
    category: 'Automation',
    summary: 'Extract, parse, validate, and file complex physical and digital documents—such as contracts, medical notes, invoices, and compliance forms—into structured databases.',
    problem: 'Physicians, attorneys, underwriters, and compliance officers spend up to 4 hours per day compiling mandatory clinical notes, case filings, and regulatory audit summaries. Administrative burnout is at an all-time high across licensed professions.',
    traditionalBreakdown: [
      'Manual charting forces healthcare clinicians to spend 2 hours typing for every 1 hour with patients.',
      'Contract reviews require paralegals to manually skim hundreds of pages for standard indemnification clauses.',
      'Copy-paste charting creates compliance vulnerabilities and billing audit clawbacks.',
      'High administrative burden directly causes professional burnout and staff turnover.',
    ],
    approach: 'NexAgent engineers ambient perception and structured documentation engines. During consultations or case meetings, our systems listen securely, extract domain entities against strict medical or legal ontologies, and draft verified documentation with one-click review.',
    systemComponents: [
      {
        name: 'Ambient Acoustic Perception Ingress',
        description: 'Multi-microphone audio pipeline isolating primary speaker dialogue and suppressing room noise.',
        badge: 'Ingress',
      },
      {
        name: 'Domain Ontology Parser',
        description: 'Specialized language models mapped to SNOMED-CT, ICD-10, and statutory legal taxonomies.',
        badge: 'Intelligence',
      },
      {
        name: 'EHR / DMS Transaction Driver',
        description: 'FHIR and HL7 compliant connectors writing notes directly to Epic, Cerner, or document vaults.',
        badge: 'Automation',
      },
      {
        name: 'Digital Signature & Compliance Ledger',
        description: 'Immutable digital signature verification and audit logging ensuring HIPAA and legal privilege preservation.',
        badge: 'Governance',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Ambient Encounter Capture',
        description: 'During patient consultations or legal client meetings, dialogue is streamed over encrypted, zero-egress audio pipelines.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Ontology Entity Extraction',
        description: 'Symptoms, diagnoses, lab orders, and legal statutes are parsed into structured FHIR or legal document schemas.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Automated Note Synthesis',
        description: 'A comprehensive SOAP note or legal case summary is synthesized in the exact institutional style required.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'One-Click Review & EHR Sync',
        description: 'The practitioner reviews the generated brief, applies digital signature, and the record commits instantly to the EHR.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Hospital networks, clinical practices, and outpatient surgical centers.',
      'Enterprise legal departments and commercial law firms.',
      'Financial compliance and anti-money laundering (AML) auditing groups.',
      'Insurance underwriters processing multi-page claims and appraisals.',
    ],
    industries: ['healthcare', 'financial-services'],
    relatedTechnology: ['voice-ai', 'ai-agents', 'software'],
    relatedProducts: ['model-010'],
    relatedCaseStudies: ['autonomous-claims-orchestration'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Deploy Documentation Automation',
    seo: {
      title: 'Intelligent Document Extraction & Compliance | NexAgent Solutions',
      description: 'Automate clinical charting, legal briefs, and compliance reports with ambient listening, domain ontology mapping, and direct EHR/database integration.',
      canonicalUrl: 'https://nexagent.group/solutions/documentation-automation',
    },
  },
  {
    id: 'sol-custom-ai-systems',
    slug: 'custom-ai-systems',
    name: 'Bespoke Enterprise AI Systems & Neural Architectures',
    category: 'Intelligence',
    summary: 'Architect and deploy specialized end-to-end artificial intelligence systems engineered around your exact proprietary workflows, data fences, and regulatory constraints.',
    problem: 'Off-the-shelf software and public AI APIs cannot solve specialized, high-stakes operational workflows. They lack domain context, risk leaking proprietary data, and fail when exposed to complex multi-step corporate reasoning.',
    traditionalBreakdown: [
      'Generic third-party SaaS forces businesses to contort their unique workflows to fit rigid software constraints.',
      'Public LLM APIs suffer from unpredictable downtime, rate limiting, and shifting prompt responses.',
      'Regulated industries cannot send customer data to shared multi-tenant cloud servers without compliance breaches.',
      'Lack of full code and model ownership creates long-term technological vulnerability.',
    ],
    approach: 'NexAgent partners directly with your executive leadership to design, build, and deploy custom sovereign AI runtimes. We fine-tune dedicated models on your private data, host them within sovereign compute enclaves, and transfer 100% intellectual property ownership to your company.',
    systemComponents: [
      {
        name: 'Private Sovereign Ingress Pipeline',
        description: 'Air-gapped data ingestion connectors supporting sovereign cloud, on-premise, or hybrid VPC hosting.',
        badge: 'Ingress',
      },
      {
        name: 'Specialized Neural Reasoning Core',
        description: 'Domain-adapted neural models fine-tuned specifically for your industry terminology and decision trees.',
        badge: 'Intelligence',
      },
      {
        name: 'Deterministic Verification Layer',
        description: 'Hard mathematical checks and business logic validators guaranteeing zero hallucinations in outputs.',
        badge: 'Governance',
      },
      {
        name: 'Dedicated API & SDK Interface',
        description: 'Custom microservices exposing the AI capabilities to your web apps, mobile apps, and internal tools.',
        badge: 'Integration',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Operational Discovery & Architectural Mapping',
        description: 'We audit your proprietary workflows, data schemas, and edge cases to construct the technical specification.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Domain Model Fine-Tuning & Validation',
        description: 'We curate private training datasets, fine-tune models, and benchmark accuracy against strict gold standards.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Sovereign Enclave Deployment',
        description: 'The system is deployed into your private cloud infrastructure with automated monitoring and load balancing.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'IP Transfer & Ongoing Optimization',
        description: 'Full source code, weights, and documentation are transferred to you with ongoing enterprise support.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Enterprises with unique proprietary workflows that standard software cannot handle.',
      'Regulated organizations requiring air-gapped data sovereignty and zero third-party egress.',
      'Ambitious companies seeking a permanent competitive moat through custom technology.',
      'Leadership teams wanting to own their technology assets rather than rent SaaS.',
    ],
    industries: ['financial-services', 'healthcare', 'b2b-sales', 'hospitality'],
    relatedTechnology: ['ai-agents', 'automation', 'software'],
    relatedProducts: ['model-010', 'event-mesh-runtime'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Design a Custom AI System',
    seo: {
      title: 'Bespoke Enterprise AI Systems & Neural Architectures | NexAgent Solutions',
      description: 'Engineer and deploy private, sovereign custom AI systems tailored to your exact business logic with 100% code and IP ownership.',
      canonicalUrl: 'https://nexagent.group/solutions/custom-ai-systems',
    },
  },
  {
    id: 'sol-crm-systems',
    slug: 'crm-systems',
    name: 'System Integration, API Middleware & ERP Connectors',
    category: 'Integration',
    summary: 'Build robust bi-directional integration bridges connecting your ERP, CRM, accounting tools, e-commerce platforms, and legacy databases into a unified real-time data mesh.',
    problem: 'Every department in a modern company uses different software: Sales uses Salesforce, Support uses Zendesk, Accounting uses QuickBooks or NetSuite, and Operations uses custom databases. Data silos prevent cross-functional collaboration and real-time visibility.',
    traditionalBreakdown: [
      'Brittle Zapier or webhook scripts fail silently, creating mismatched inventory and billing errors.',
      'Nightly batch sync jobs mean decisions are made on 24-hour outdated operational metrics.',
      'Employees spend hours manually re-entering records from one software tool into another.',
      'Custom point-to-point integrations become an unmaintainable nightmare of tangled code.',
    ],
    approach: 'NexAgent engineers enterprise-grade integration middleware with idempotent message queues, automated schema translation, and two-phase commit guarantees. Any update in one system propagates reliably across all connected platforms in real time.',
    systemComponents: [
      {
        name: 'Event Stream & Webhook Ingress',
        description: 'High-throughput event broker receiving state changes via webhooks, CDC, and REST APIs.',
        badge: 'Ingress',
      },
      {
        name: 'Schema Mapping & Transformation Arbiter',
        description: 'Automated data normalization translating differing entity formats across platforms.',
        badge: 'Intelligence',
      },
      {
        name: 'Idempotent Transaction Dispatcher',
        description: 'Guaranteed-delivery queues with automatic retries, dead-letter monitoring, and rollback.',
        badge: 'Integration',
      },
      {
        name: 'Real-Time Health & Alert Dashboard',
        description: 'Comprehensive telemetry monitoring API latency, sync health, and webhook delivery status.',
        badge: 'Monitoring',
      },
    ],
    workflows: [
      {
        step: '01',
        name: 'Trigger Event Ingress',
        description: 'A new deal closes in the CRM or a payment succeeds in Stripe, generating an immediate event payload.',
        systemLayer: 'Ingress & Perception',
      },
      {
        step: '02',
        name: 'Schema Normalization & Deduplication',
        description: 'The middleware maps customer IDs, formats currencies, and verifies entity resolution rules.',
        systemLayer: 'Intelligence & Routing',
      },
      {
        step: '03',
        name: 'Bi-Directional Multi-System Dispatch',
        description: 'ERP invoices, warehouse fulfillment orders, and provisioning accounts are updated in parallel.',
        systemLayer: 'Execution & Automation',
      },
      {
        step: '04',
        name: 'Delivery Verification & Audit Trail',
        description: 'Every transaction is confirmed with cryptographic timestamps and stored in a searchable audit log.',
        systemLayer: 'Verification & Audit',
      },
    ],
    whoItIsFor: [
      'Companies with 5+ disparate software tools that need to speak seamlessly to each other.',
      'Enterprises integrating acquisitions or multiple subsidiary databases.',
      'E-commerce operations coordinating multi-warehouse inventory and accounting.',
      'Organizations requiring real-time data flow without manual data entry staff.',
    ],
    industries: ['b2b-sales', 'financial-services', 'hospitality'],
    relatedTechnology: ['automation', 'software'],
    relatedProducts: ['event-mesh-runtime'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    ctaText: 'Connect Your Systems',
    seo: {
      title: 'System Integration, API Middleware & ERP Connectors | NexAgent Solutions',
      description: 'Connect enterprise CRM, ERP, billing, and database systems with reliable, real-time bi-directional integration middleware and zero-loss guarantees.',
      canonicalUrl: 'https://nexagent.group/solutions/crm-systems',
    },
  },
];
