import { TechnologyItem } from './types';

export const technologies: TechnologyItem[] = [
  {
    id: 'tech-ai-agents',
    slug: 'ai-agents',
    name: 'Autonomous Multi-Agent Consensus & Execution',
    category: 'AI',
    shortDescription: 'Multi-agent coordination runtimes executing complex enterprise workflows with deterministic state verification and cryptographic audit trails.',
    description: 'NexAgent multi-agent architectures transition artificial intelligence from single-turn chat prompts into multi-step, autonomous execution systems. Specialized agents operate within hierarchical consensus loops, verifying intermediate states before executing database transactions or external API operations.',
    whyItMatters: 'Enterprise processes rarely conform to single prompt-response patterns. Real operational throughput requires asynchronous task decomposition, self-correcting validation loops, and strict transaction rollback capabilities when exceptions occur.',
    whatItEnables: [
      'Multi-agent task decomposition across disparate systems of record.',
      'Automated peer-verification loops reducing hallucinations to near-zero.',
      'ACID-compliant state transaction commits with cryptographic rollbacks.',
      'Human-in-the-loop exception delegation without workflow disruption.',
    ],
    systemArchitecture: [
      'Task Ingestion & Semantic Decomposition Gateway',
      'Multi-Agent Consensus Arbiter & State Vector Registry',
      'Sandboxed Tool & Execution Container Enclave',
      'Deterministic Audit Ledger & Rollback Coordinator',
    ],
    capabilities: [
      'Autonomous Task Decomposition',
      'Multi-Model Consensus Routing',
      'Deterministic State Verification',
      'Sub-Second Transaction Commit',
      'Air-Gapped Tool Execution',
    ],
    applications: [
      'Automated insurance claims adjudication',
      'Complex supply chain purchase order reconciliation',
      'Autonomous treasury settlement and liquidity rebalancing',
      'Multi-system customer operations and resolution',
    ],
    relatedSolutions: ['business-automation', 'sales-automation', 'crm-systems'],
    relatedIndustries: ['healthcare', 'financial-services', 'b2b-sales'],
    relatedProducts: ['model-010'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    featured: true,
    ctaText: 'Discuss Agent Architecture',
    seo: {
      title: 'Autonomous Multi-Agent Systems & Runtimes | NexAgent Technology',
      description: 'Explore NexAgent autonomous multi-agent consensus runtimes: deterministic task decomposition, zero-hallucination verification, and enterprise execution.',
      canonicalUrl: 'https://nexagent.group/technology/ai-agents',
    },
  },
  {
    id: 'tech-cloud-infrastructure',
    slug: 'cloud-infrastructure',
    name: 'Sovereign Cloud & Bare-Metal GPU Enclaves',
    category: 'Infrastructure',
    shortDescription: 'Hardware-isolated Tier-IV compute infrastructure engineered for private AI training, zero-egress inference, and data residency compliance.',
    description: 'NexAgent Cloud Infrastructure delivers dedicated bare-metal NVIDIA H100 and B200 GPU clusters with private fiber interconnects across the US, UK, EU, and UAE. Systems are architected with hardware-enforced memory encryption and local regulatory sovereignty.',
    whyItMatters: 'Regulated enterprises cannot expose sensitive intellectual property, patient health records, or customer transaction data to public shared multi-tenant cloud APIs. Sovereign infrastructure guarantees complete data residency and deterministic throughput.',
    whatItEnables: [
      'Cryptographically isolated compute enclaves with zero outbound data leakage.',
      'Deterministic sub-120ms time-to-first-token inference across dedicated clusters.',
      'Compliance with GDPR, HIPAA, FedRAMP, and local sovereign data residency mandates.',
      'Direct fiber cross-connects to enterprise on-premise datacenters.',
    ],
    systemArchitecture: [
      'Bare-Metal RoCE v2 InfiniBand Fabric (3.2 Tbps per node)',
      'Hardware-Enforced Confidential Computing Enclaves (AMD SEV-SNP)',
      'Zero-Trust Identity & Ephemeral Key Attestation (HashiCorp Boundary)',
      'Real-Time GPU Telemetry & Thermal Throttling Mitigation Engine',
    ],
    capabilities: [
      'Bare-Metal GPU Provisioning',
      'Zero Data Egress Guarantees',
      'Multi-Region Sovereign Routing',
      'Sub-120ms Latency SLA',
      'Dedicated Private Interconnects',
    ],
    applications: [
      'On-premise / sovereign neural model inference',
      'Highly regulated healthcare diagnostic pipeline processing',
      'Real-time sovereign financial ledger computation',
      'Confidential multi-party data computation',
    ],
    relatedSolutions: ['business-automation', 'documentation-automation'],
    relatedIndustries: ['healthcare', 'financial-services'],
    relatedProducts: ['model-010', 'event-mesh-runtime'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    featured: true,
    ctaText: 'Evaluate Sovereign Infrastructure',
    seo: {
      title: 'Sovereign Cloud & Bare-Metal GPU Infrastructure | NexAgent Technology',
      description: 'Tier-IV private compute infrastructure, bare-metal GPU enclaves, and sovereign multi-region hosting engineered for regulated enterprise workloads.',
      canonicalUrl: 'https://nexagent.group/technology/cloud-infrastructure',
    },
  },
  {
    id: 'tech-voice-ai',
    slug: 'voice-ai',
    name: 'Sub-180ms Conversational Voice Runtimes',
    category: 'Runtime',
    shortDescription: 'Ultra-low latency conversational audio mesh with human turn-taking, real-time interruption handling, and ambient acoustic isolation.',
    description: 'NexAgent Voice AI architectures combine distributed edge WebRTC media streaming with streaming speech-to-speech neural models. The system processes conversational input, detects interruption cues within 40ms, and generates responses with natural pacing.',
    whyItMatters: 'Legacy voice bots suffer from 800ms–2000ms latency gaps and clumsy turn-taking, causing frustration and immediate call abandonment. Sub-180ms roundtrip audio delivers true human-cadence conversations suitable for high-stakes customer interactions.',
    whatItEnables: [
      'Sub-180ms end-to-end voice latency over global WebRTC edge networks.',
      'Dynamic interruption handling that halts synthesis instantaneously upon user speech.',
      'Ambient acoustic filtering for noisy industrial, retail, or hospital environments.',
      'Simultaneous multi-lingual transcription and translation in real time.',
    ],
    systemArchitecture: [
      'Edge WebRTC Ingress Mesh (Global POPs)',
      'Streaming Acoustic Neural Feature Extractor',
      'Low-Latency Bidirectional Token Transformer',
      'High-Fidelity Neural Vocoder with Real-Time Buffer Truncation',
    ],
    capabilities: [
      'Sub-180ms Audio Roundtrip',
      'Instant Interruption Detection (<40ms)',
      'Acoustic Background Suppression',
      'Multilingual Zero-Shot Switching',
      'Direct SIP / Telephony Trunking',
    ],
    applications: [
      'High-volume hospitality reservations and guest concierge',
      'Automated medical appointment scheduling and triage',
      '24/7 financial concierge and account verification',
      'Outbound enterprise compliance check-ins',
    ],
    relatedSolutions: ['sales-automation', 'business-automation'],
    relatedIndustries: ['hospitality', 'healthcare'],
    relatedProducts: ['model-010'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    featured: true,
    ctaText: 'Test Voice Architecture',
    seo: {
      title: 'Sub-180ms Conversational Voice AI Systems | NexAgent Technology',
      description: 'Ultra-low latency voice AI with sub-180ms response time, real-time interruption handling, and WebRTC telephony mesh integration.',
      canonicalUrl: 'https://nexagent.group/technology/voice-ai',
    },
  },
  {
    id: 'tech-automation',
    slug: 'automation',
    name: 'Deterministic Workflow Automation & Integration',
    category: 'Automation',
    shortDescription: 'State-synchronizing automation engines connecting modern AI agents directly with legacy ERPs, CRMs, and core banking mainframes.',
    description: 'NexAgent Automation bridges generative reasoning with transactional determinism. While AI models evaluate unstructured inputs, our automation mesh translates outputs into strictly validated, schema-enforced API calls across legacy enterprise infrastructure.',
    whyItMatters: 'Generative models alone cannot be trusted with irreversible enterprise transactions without verification. Deterministic automation ensures that all agent actions execute with idempotent safety, full logging, and transaction rollbacks.',
    whatItEnables: [
      'Idempotent execution preventing duplicate payments or orders.',
      'Bi-directional state synchronization across Salesforce, SAP, Oracle, and Epic.',
      'Comprehensive audit trails recording every prompt, tool call, and database state.',
      'Microsecond webhook dispatch across distributed enterprise message queues.',
    ],
    systemArchitecture: [
      'Schema Validation & Action Guardrail Filter',
      'Two-Phase Commit Transaction Manager',
      'Legacy Connector Bridge (gRPC, SOAP, REST, RFC)',
      'Immutable Audit & Replay Ledger',
    ],
    capabilities: [
      'Two-Phase Commit Guarantees',
      'Idempotent API Orchestration',
      'Legacy ERP Protocol Bridging',
      'Full Transaction Replay Logging',
      'Zero-Loss Queue Fault Tolerance',
    ],
    applications: [
      'Automated ERP purchase order validation and supplier dispatch',
      'Cross-system CRM record unification and deduplication',
      'Automated regulatory filing and compliance check generation',
      'End-to-end employee onboarding and IT provisioning',
    ],
    relatedSolutions: ['business-automation', 'documentation-automation', 'crm-systems'],
    relatedIndustries: ['b2b-sales', 'financial-services', 'healthcare'],
    relatedProducts: ['event-mesh-runtime'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    featured: true,
    ctaText: 'Design Enterprise Workflows',
    seo: {
      title: 'Deterministic Enterprise Workflow Automation | NexAgent Technology',
      description: 'Connect AI agents to legacy ERP, CRM, and core systems with deterministic two-phase commit guarantees and cryptographic audit logs.',
      canonicalUrl: 'https://nexagent.group/technology/automation',
    },
  },
  {
    id: 'tech-software',
    slug: 'software',
    name: 'Mission-Critical Enterprise Software & Cognitive Middleware',
    category: 'Software',
    shortDescription: 'Custom, high-concurrency software architectures combining distributed systems engineering with embedded autonomous intelligence.',
    description: 'NexAgent designs and engineers specialized enterprise software platforms. From sovereign patient data meshes to algorithmic financial clearing rails, our software layers replace fragmented SaaS sprawl with unified, modern software systems.',
    whyItMatters: 'Off-the-shelf SaaS stacks create siloed operational data, exorbitant per-seat licensing fees, and vendor lock-in. Custom cognitive software gives organizations total control over their data architecture and competitive advantages.',
    whatItEnables: [
      'Consolidation of fragmented third-party SaaS tools into an owned platform.',
      'Full architectural ownership with zero per-seat licensing penalties.',
      'High-throughput microservice architectures scaling horizontally.',
      'Direct integration with internal data lakes and proprietary business logic.',
    ],
    systemArchitecture: [
      'Distributed Microservices Architecture (Go, Rust, TypeScript)',
      'High-Throughput In-Memory State Cache (Redis / DragonFly)',
      'Event-Driven Reactive Data Pipeline (Apache Kafka / Redpanda)',
      'Modern Editorial & Operator Frontend Interface (Next.js, WebGL)',
    ],
    capabilities: [
      'Microservice Architecture Design',
      'Full IP Ownership & Source Code Delivery',
      'Sub-50ms API Response Benchmarks',
      'Zero-Downtime Rolling Deployments',
      'Sovereign Cloud Native Packaging',
    ],
    applications: [
      'Proprietary vertical operating systems for logistics and supply chain',
      'Custom institutional trading and liquidity routing portals',
      'Unified enterprise telemetry and operational command centers',
      'Specialized healthcare clinical trial and patient monitoring systems',
    ],
    relatedSolutions: ['business-automation', 'crm-systems'],
    relatedIndustries: ['b2b-sales', 'hospitality', 'financial-services'],
    relatedProducts: ['model-010', 'event-mesh-runtime'],
    status: 'PUBLISHED',
    readiness: 'ACTIVE',
    featured: false,
    ctaText: 'Explore Custom Software',
    seo: {
      title: 'Mission-Critical Enterprise Software Engineering | NexAgent Technology',
      description: 'Engineered custom software platforms, cognitive middleware, and high-concurrency systems replacing fragmented SaaS tools.',
      canonicalUrl: 'https://nexagent.group/technology/software',
    },
  },
];
